apiVersion: cert-manager.io/v1alpha2
   kind: Cluster-Issuer
   metadata:
     name: letsencrypt-prod
   spec:
     acme:
       # The ACME server URL
       server: https://acme-v02.api.letsencrypt.org/directory
       # Email address used for ACME registration
       email: sysadmin@dollarsmart.co
       # Name of a secret used to store the ACME account private key
       privateKeySecretRef:
         name: letsencrypt-privatekey
       # Enable the HTTP-01 challenge provider
       solvers:
       - http01:
           ingress:
             class: front