apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dollarsmartglobal-com-cert
  namespace: dsg-front # Name space of ingress
spec:
  dnsNames:
  - dev-www.dollarsmartglobal.com # DNS name 
  issuerRef:
    kind: ClusterIssuer
    name: aws-issuer #Cluster Issuer Name
  secretName: dollarsmartglobal-com-tls #Store the Private and Public Key